baseURL = "https://jamespatten.co/"
languageCode = "en-us"
title = "James Patten"
theme = "digitalgarden"

googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "My Digital Garden on the Internet"
  images = ['/digital-garden-logo.png']
  enableSearch = true


[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Blog'
  url = '/articles'
  weight = 3
[[menu.main]]
  name = 'Portfolio'
  url = '/portfolio'
  weight = 4
[[menu.main]]
  name = 'Stack'
  url = '/stack'
  weight = 5
[[menu.main]]
  name = 'Links'
  params.header = true
  weight = 6
[[menu.main]]
  name = 'Data Importer'
  url = 'https://dataimporter.co'
  weight = 7


[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/jamesgpatten/'
  weight = 3
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/jape-dev'
  weight = 2
[[menu.social]]
  name = 'Email'
  url = 'mailto:jamespatten1996@gmail.com'
  weight = 8

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
